src/Entity/PageData.php
<?php

namespace App\Entity;

use App\Components\Language\CurrentLanguage;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Page
 * @package App\Entity
 * @ORM\Entity
 * @ORM\Table(name="page_data")
 */
class PageData
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Page", inversedBy="data")
     * @ORM\JoinColumn(name="page_id", referencedColumnName="id")
     */
    private $page;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=191)
     */
    private $language;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @ORM\Column(type="string", length=191, nullable=true)
     */
    private $marking;

    /**
     * @ORM\OneToMany(targetEntity="PageBody", mappedBy="entity", cascade={"persist", "remove"})
     */
    private $body;

    public function __construct()
    {
        $this->body = new ArrayCollection();
        $this->language = CurrentLanguage::$language;;
        $this->created = new \DateTime();
        $this->updated = new \DateTime();
        $this->marking = 'draft';
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * @param mixed $page
     */
    public function setPage($page): void
    {
        $this->page = $page;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * @param mixed $language
     */
    public function setLanguage($language): void
    {
        $this->language = $language;
    }

    /**
     * @return mixed
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * @param mixed $created
     */
    public function setCreated($created): void
    {
        $this->created = $created;
    }

    /**
     * @return mixed
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * @param mixed $updated
     */
    public function setUpdated($updated): void
    {
        $this->updated = $updated;
    }

    /**
     * @return mixed
     */
    public function getMarking()
    {
        return $this->marking;
    }

    /**
     * @param mixed $marking
     */
    public function setMarking($marking): void
    {
        $this->marking = $marking;
    }

    /**
     * @return mixed
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * @param PageBody $body
     */
    public function addBody(PageBody $body): void
    {
        $body->setEntity($this);
        $this->body->add($body);
    }

    public function getFieldBody(){
        return $this->body->first();
    }
}

templates/Page/add.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-add">
    <div class="block-content">
        {{ form(form) }}
    </div>
  </div>
{% endblock %}

templates/Page/delete.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-delete">
    <div class="block-content">
        {{ form(form) }}
    </div>
  </div>

{% endblock %}

templates/Page/edit.html.twig
{% extends 'page_default.html.twig' %}

{% block regionRight %}
  <div class="block block--page-edit">
    <div class="block-content">
      {{ form(form) }}
    </div>
  </div>

{% endblock %}

templates/Page/list.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-list">
    <div class="block-content">
      <div class="list list--page-list">
        {% for page in pages %}
          <div class="list-item">
            {{  include('Page/ViewMode/teaser.html.twig', { 'item' : page } )  }}
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="block-navigation">
      <ul class="pager">
        {% if navigator.pager > 1 %}
          <li class="pager-item"><a href="{{ path('page_list', { 'page' : navigator.pager - 1 }) }}">back</a></li>
        {% endif %}
        <li class="pager-item">{{ navigator.pager }}</li>
        {% if navigator.pager*navigator.limit < navigator.total %}
          <li class="pager-item"><a href="{{ path('page_list', { 'page' : navigator.pager + 1 }) }}">next</a></li>
        {% endif %}
      </ul>
    </div>
  </div>


{% endblock %}

templates/Page/page_comments.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-view">
    <div class="block-content">
      <h2 class="field field-title">{{ page.title }}</h2>
      <div class="field field-comments">
        <div class="comment-preview">
          <h2 class="comment-title">Comments</h2>
          <div class="list">
              {% for item in comments %}
                <div class="list-item">
                    {{ include('Comments/ViewMode/teaser.html.twig', {'item' : item }) }}
                  <ul>
                    <li><a href="{{ path('comment_edit', { 'id' : item.id }) }}">Edit</a></li>
                    <li><a href="{{ path('comment_delete', { 'id' : item.id }) }}">Delete</a></li>
                  </ul>
                </div>
              {% endfor %}
          </div>
        </div>
      </div>

    </div>
    <div class="block-navigation">
      <ul class="pager">
          {% if navigator.pager > 1 %}
            <li class="pager-item"><a href="{{ path('page_comments', { 'id' : page.id, 'pager' : navigator.pager - 1 }) }}">back</a></li>
          {% endif %}
        <li class="pager-item">{{ navigator.pager }}</li>
          {% if navigator.pager*navigator.limit < navigator.total %}
            <li class="pager-item"><a href="{{ path('page_comments', { 'id' : page.id, 'pager' : navigator.pager + 1 }) }}">next</a></li>
          {% endif %}
      </ul>
    </div>
  </div>

{% endblock %}

templates/Page/search.html.twig
{% extends 'page_default.html.twig' %}

{% block main %}
  <div class="block block--page-list">
    <div class="block-content">
      {{ form(form) }}
      <div class="list list--page-list">
        {% for page in pages %}
          <div class="list-item">
            {{  include('Page/ViewMode/teaser.html.twig', { 'item' : page } )  }}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>


{% endblock %}

templates/Page/view.html.twig
{% extends 'page_default.html.twig' %}

{% block page_title %}{{ page_data.title }}{% endblock %}

{% block main %}
     <article class="block block--page-view page-view page-{{ page_data.page.id }}">
         <div class="block-content">
             <div class="fields fields-top">
                 <div class="field field-body">{{ page_data.fieldBody.body }}</div>
                 <div class="list-link">
                     {#{% if page.category %}#}
                     {#<div class="list-link-item page-category">{{ page.category.name }}</div>#}
                     {#{% endif %}#}
                     <div class="list-link-item page-created">{{ page_data.created|date('d-m-Y') }}</div>
                 </div>
             </div>
             {#<div class="field field-comments">#}
             {#<div class="comment-preview">#}
             {#<h2 class="comment-title">Comments</h2>#}
             {#{{ form(comment_form) }}#}
             {#<div class="list">#}
             {#{% for item in page_comments %}#}
             {#<div class="list-item">#}
             {#{{ include('Comments/ViewMode/teaser.html.twig', {'item' : item }) }}#}
             {#<ul>#}
             {#<li><a href="{{ path('comment_edit', { 'id' : item.id }) }}">Edit</a></li>#}
             {#<li><a href="{{ path('comment_delete', { 'id' : item.id }) }}">Delete</a></li>#}
             {#</ul>#}
             {#</div>#}
             {#{% endfor %}#}
             {#</div>#}
             {#</div>#}
             {#</div>#}

         </div>
     </article>
 {% endblock %}